services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.6
    plan: free
    autoDeploy: true
